import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";
import { ThemeProvider } from "@/components/theme-provider";
import LayoutComponent from "./_Components/layout";
import { AlertShowHideProvider } from "./Context/SnackBar";
import ReduxProvider from "./ReduxProvider";

export const metadata: Metadata = {
  title: "eCom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <ReduxProvider>
          <AlertShowHideProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <AuthProvider>
             
                <LayoutComponent>{children}</LayoutComponent>
              </AuthProvider>
            </ThemeProvider>
          </AlertShowHideProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}